version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./src/infra/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
